"""s1_5_1 my task placements

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-23 13:01:32.312519
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "my_task_placements",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("bucket", sa.String(length=24), nullable=False),
        sa.Column("position", sa.String(length=64, collation="C"), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "bucket in ('recently_assigned','today','this_week','later')",
            name=op.f("ck_my_task_placements_bucket"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_my_task_placements_task_id_tasks")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_my_task_placements_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", "task_id", name=op.f("pk_my_task_placements")),
    )
    op.create_index(
        "ix_my_task_placements_user_bucket",
        "my_task_placements",
        ["user_id", "bucket", "position"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_my_task_placements_user_bucket", table_name="my_task_placements")
    op.drop_table("my_task_placements")
    # ### end Alembic commands ###
