"""s2_3_1 custom fields: field_defs, project_fields, field_values

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-24 06:39:11.550028
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "field_defs",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_library", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "type in ('text', 'number', 'single_select', 'multi_select', 'date', 'people', 'checkbox', 'url', 'currency', 'percent')",
            name=op.f("ck_field_defs_type"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_field_defs_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], name=op.f("fk_field_defs_workspace_id_workspaces")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_defs")),
    )
    op.create_index(
        op.f("ix_field_defs_workspace_id"), "field_defs", ["workspace_id"], unique=False
    )
    op.create_table(
        "field_values",
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("field_id", sa.Uuid(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["field_id"], ["field_defs.id"], name=op.f("fk_field_values_field_id_field_defs")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_field_values_task_id_tasks")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_field_values_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("task_id", "field_id", name=op.f("pk_field_values")),
    )
    # Filters by field value (S2.3.2) read this: docs/architecture/data-model.md §4.
    op.create_index(
        "ix_field_values_value_gin", "field_values", ["value"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "project_fields",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("field_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.String(length=64, collation="C"), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["field_id"], ["field_defs.id"], name=op.f("fk_project_fields_field_id_field_defs")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_project_fields_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("project_id", "field_id", name=op.f("pk_project_fields")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_fields")
    op.drop_index("ix_field_values_value_gin", table_name="field_values")
    op.drop_table("field_values")
    op.drop_index(op.f("ix_field_defs_workspace_id"), table_name="field_defs")
    op.drop_table("field_defs")
    # ### end Alembic commands ###
